# Generated by Django 2.2.12 on 2022-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20220307_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Completo'),
        ),
    ]
